"""Auto-generated learned predictor — DO NOT edit manually.
Generated by ml_training/03_export_for_bot.py from logreg_v1.json
Trained on 257 trades (2026-01-15 to 2026-05-22).

Metrics:
  in-sample acc:  62.6%
  CV acc (mean):  57.6%
  CV brier (mean):0.2759
  baseline brier: 0.2874
"""
import math

FEATURES = ['prob_model', 'ask', 'edge', 'trend', 'trend_abs', 'dist_pct', 'roc60_bps', 'sigma', 't_remain', 'hour', 'coin_btc', 'coin_sol', 'dir_up', 'is_cheap', 'is_mid_price', 'trend_weak', 'trend_mid', 'trend_dir_aligned']
INTERCEPT = -0.0313387551945255
COEFS = {'prob_model': -0.02792794694053025, 'ask': 0.3803659113068971, 'edge': -0.3517977944969701, 'trend': -0.11409403857135611, 'trend_abs': -0.6508964221009802, 'dist_pct': -0.6162583507688522, 'roc60_bps': 0.5522323217053069, 'sigma': -0.05019687085302539, 't_remain': 0.00442335821604086, 'hour': 0.09993867074046481, 'coin_btc': 0.17911719327925965, 'coin_sol': 0.2379622336251379, 'dir_up': -0.35767659703572413, 'is_cheap': 0.018046794768248952, 'is_mid_price': 0.142732344891172, 'trend_weak': -0.3023350421352366, 'trend_mid': -0.14638690786553893, 'trend_dir_aligned': -0.20906447272769238}
SCALER_MEAN = [0.8317455652682637, 0.5985214007782101, 0.2154824902723735, 0.1263703524305891, 1.5418738309350175, 0.09133834352262554, -0.3332806997932807, 0.0018864396887159534, 472.24124513618676, 12.929961089494164, 0.3540856031128405, 0.3735408560311284, 0.46303501945525294, 0.1245136186770428, 0.5136186770428015, 0.36964980544747084, 0.3151750972762646, 0.9961089494163424]
SCALER_SCALE = [0.06094449771660609, 0.09676555430113103, 0.12500331779575452, 2.818112405604828, 2.362276885988396, 1.184387391053522, 11.590126599003622, 0.0014624304397507701, 215.27176781613304, 3.636573460752712, 0.47823528600580745, 0.48374382156949586, 0.49863171801774353, 0.33016659043729846, 0.49981449722432414, 0.4827098784778678, 0.4645855737462817, 0.06225680933852139]


def _build_feature_dict(coin: str, direction: str, ask: float, prob_model: float,
                        edge: float, trend: float, dist_pct: float, roc60_bps: float,
                        sigma: float, t_remain: int, hour: int) -> dict:
    """Construct the full feature dict (same schema as training)."""
    return {
        "prob_model":  prob_model,
        "ask":         ask,
        "edge":        edge,
        "trend":       trend,
        "trend_abs":   abs(trend),
        "dist_pct":    dist_pct,
        "roc60_bps":   roc60_bps,
        "sigma":       sigma,
        "t_remain":    t_remain,
        "hour":        hour,
        "coin_btc":    1 if coin == "BTC" else 0,
        "coin_sol":    1 if coin == "SOL" else 0,
        "dir_up":      1 if direction == "UP" else 0,
        "is_cheap":    1 if ask < 0.50 else 0,
        "is_mid_price":1 if 0.50 <= ask < 0.62 else 0,
        "trend_weak":  1 if abs(trend) < 1.0 else 0,
        "trend_mid":   1 if 1.0 <= abs(trend) < 1.5 else 0,
        "trend_dir_aligned": 1 if (trend > 0 and direction == "UP")
                             or (trend < 0 and direction == "DOWN") else 0,
    }


def learned_win_prob(coin: str, direction: str, ask: float, prob_model: float,
                     edge: float, trend: float, dist_pct: float, roc60_bps: float,
                     sigma: float, t_remain: int, hour: int) -> float:
    """Compute calibrated win probability for a candidate trade.
    Returns float in [0.01, 0.99]."""
    f = _build_feature_dict(coin, direction, ask, prob_model, edge, trend,
                            dist_pct, roc60_bps, sigma, t_remain, hour)
    z = INTERCEPT
    for i, name in enumerate(FEATURES):
        x = (f.get(name, 0.0) - SCALER_MEAN[i]) / SCALER_SCALE[i]
        z += COEFS[name] * x
    p = 1.0 / (1.0 + math.exp(-z))
    return max(0.01, min(0.99, p))
